# SPDX-FileCopyrightText: 2023 Inditex
#
# SPDX-License-Identifier: Apache-2.0

cerws:
  common:
    rest:
      client:
        github-rest-client:
          username: CERWS_GH_USERNAME
          password: CERWS_GH_PASSWORD